name: 🧪 CI Flow

on: [pull_request, push, workflow_dispatch]

jobs:
  build-mods:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      mods-artifact-id: ${{ steps.upload-mods.outputs.artifact-id }}
    steps:
      - name: ⚙️ Checkout code
        uses: actions/checkout@v6

      - name: ⚙️ Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: microsoft

      - name: ⚙️ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: 🔧 Build all Mods
        shell: bash
        run: ./gradlew build

      - name: 🩹 Get Short SHA
        id: short-sha
        uses: hudsonm62/short-sha@v1

      - name: 📤 Upload Built Mods
        uses: actions/upload-artifact@v7
        id: upload-mods
        with:
          name: mods-artifacts_${{ steps.short-sha.outputs.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: build/libs/*.jar
          compression-level: 9
          if-no-files-found: error
