name: 📦 Releaser

on: workflow_dispatch

defaults:
  run:
    shell: pwsh

jobs:
  gh-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: ⚙️ Checkout code
        uses: actions/checkout@v6

      - name: 🩹 Read mod version
        id: version
        run: |
          $Version = (Get-Content gradle.properties | Select-String '^mod_version=').ToString().Split('=')[1]
          echo "mod_version=$Version" >> $env:GITHUB_OUTPUT

      - name: 🔍 Check Tag doesn't exist
        id: get-tag
        run: |
          $Version = "${{ steps.version.outputs.mod_version }}"
          $Tag = "v$Version"

          git fetch --tags
          $tagExists = git tag --list $Tag
          if ($tagExists) {
            throw "❌ Tag '$Tag' already exists. Aborting release."
          }
          Write-Host "✅ Tag '$Tag' does not exist. Proceeding with release."

          # Set output for next step
          echo "version=$Tag" >> $env:GITHUB_OUTPUT

      - name: 🏷️ Create Tag
        id: create-tag
        run: |
          $Tag = "${{ steps.get-tag.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$Tag" -m "$Tag"
          git push origin "$Tag"

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get-tag.outputs.version }}
          name: "Cobblemon Smartphone Pokedex App ${{ steps.get-tag.outputs.version }}"
          generate_release_notes: true
          prerelease: false
